### PR TITLE
Pipe name servers to resolvconf rather than write them to resolv.conf

### PR DESCRIPTION
**Pull request by CropCircleSys**
i don't ever use this openstack cloud stuff or whatever so if theres some mode or code path where this is making an offline image or something watch out this may break it but if this runs for you as straightforward as it looked and worked for me then great, i was in the neighborhood and a little birdie told me you needed this so try it out and let me know what you think

### CODE REVIEW

**Comment by CropCircleSys** [comment]
Thank you so much let me know what you think or if I totally screwed the pooch on this one. now of course it only works with freebsd 9+ using my patch. if you are trying to support 8.4 still could you add a case switch please? i’m not sure how openstack os selection works early on perhaps image offline mode not happen same as python standard lib.

Rationale for pull request of course being this necessary to run local verifying caching resolver such as unbound_enable from ports or local_unbound_enable in base.

**Comment by pellaeon** [comment]
Thanks, I'm testing it now.

**Comment by CropCircleSys** [comment]
Thank you sir! Very much appreciate your great contribution to FreeBSD.

**Comment by pellaeon** [comment]
Hello, I'm sorry it took a while, during testing, I found some bugs in `bsd-cloudinit` itself and committed a fix, so please rebase your pull request so that I can continue testing.
Thanks!

**Comment by CropCircleSys** [comment]
That should be all set now. Let me know if there's anything else I can do. Thanks.

**Comment by pellaeon** [comment]
Tested and works! Thanks for your contribution.

**Pull request merged**
