### PR TITLE
Implement simple user data support (script-only)

### PR DESCRIPTION
**Pull request by martymac**
Simple implementation of user data support (user data is always considered to be a script to execute).

### CODE REVIEW

**Comment by pellaeon** [comment]
Hi, thanks for the pull request, I'm in the process of building up a Jenkins environment that can build test images (currently met with some difficulty). I'll test your PR once Jenkins has been set up. (It might take weeks, track the progress [here](https://github.com/pellaeon/bsd-cloudinit/wiki/Jenkins-configuration).

**Comment by martymac** [comment]
Hi ! Good news, thanks :)

**Comment by pellaeon** [comment]
Can one of the admins verify this patch?

**Comment by pellaeon** [comment]
Can one of the admins verify this patch?

**Comment by martymac** [comment]
Hi, any news on that PR ?

**Comment by pellaeon** [comment]
Sorry, stuck at some jenkins job configuration, still not able to get normal build 😢 ,I'll try to figure it out later.

**Comment by martymac** [comment]
OK, thanks for the update :)

**Comment by martymac** [comment]
Still no news ? :)

**Comment by martymac** [comment]
HI,
Any update on that PR ?

**Comment by guest20** [comment]
I too would like user-data support.

**Comment by hartzell** [comment]
Me three.  Any update on this?

**Comment by glorieux** [comment]
Would really need this. 
What's the status?
Is there anything we can do to speed up the review process?

**Comment by martymac** [comment]
Hello,

Any news ?

**Comment by monokrome** [comment]
How about that quick turnaround time on this PR, amirite?!

**Pull request merged**
